# From Chat GPT - deploy a component library and storybook

name: CI/CD for Storybook and npm Library

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  build-storybook:
    name: Build and Deploy Storybook
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy Storybook to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ./storybook-static

  publish-library:
    name: Publish to npm registry
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Authenticate to npm
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build the library
        run: npm run build

      - name: Publish library
        run: npm publish --access public # Change access type if needed

  notify-success:
    name: Notify success
    runs-on: ubuntu-latest
    needs: [build-storybook, publish-library]
    steps:
      - name: Success notification
        run: echo "Storybook and library deployed successfully!"
